# lib/park.rb

# The Park class represents a national park with vehicles, passengers, and revenue tracking.
class Park
  attr_reader :name, :price, :vehicles

  # Initializes a Park with its name, admission price, and a list of vehicles.
  def initialize(name, price)
    @name = name           # The name of the park (e.g., Yellowstone).
    @price = price         # The admission price per adult.
    @vehicles = []         # A list of vehicles that entered the park.
  end

  # Adds a vehicle to the park.
  def add_vehicle(vehicle)
    @vehicles << vehicle
  end

  # Collects all passengers from all vehicles in the park.
  def passengers
    @vehicles.flat_map(&:passengers) # Combines all passengers from all vehicles.
  end

  # Calculates the total revenue generated by charging the admission price per adult.
  def revenue
    passengers.count(&:adult?) * @price # Multiply the number of adults by the price.
  end

  # Lists the names of all passengers, sorted alphabetically.
  def patron_names
    passengers.map(&:name).sort
  end

  # Lists the names of all minors (under 18), sorted alphabetically.
  def minors
    passengers.select { |p| !p.adult? }.map(&:name).sort
  end

  # Lists the names of all adults (18 and older), sorted alphabetically.
  def adults
    passengers.select(&:adult?).map(&:name).sort
  end
end
