# lib/park.rb

# The Park class represents a national park with vehicles, passengers, and revenue tracking.
class Park
  attr_reader :name, :price, :vehicles

  # Initialize a Park with a name, admission price, and an empty list of vehicles.
  def initialize(name, price)
    @name = name           # The unique name of the park.
    @price = price         # The admission price per adult.
    @vehicles = []         # A list to store vehicles that enter the park.
  end

  # Add a vehicle to the park's vehicle list.
  def add_vehicle(vehicle)
    @vehicles << vehicle
  end

  # List all passengers in all vehicles that entered the park.
  def passengers
    @vehicles.flat_map(&:passengers)
  end

  # Calculate revenue generated by charging the admission price for each adult passenger.
  def revenue
    num_adults = passengers.count(&:adult?) # Count only adult passengers.
    num_adults * @price                     # Multiply by the park's admission price.
  end
end
